---
# simple cloudformation template to create a S3 bucket
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  BucketName:
    Description: name of the S3 bucket getting create
    Type: String
Mappings:
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
Outputs:
