---
AWSTemplateFormatVersion: "2010-09-09"

Description: 'AWS Cloudformation template for Security group configuration'

Metadata:
  License: Apache-2.0

Parameters:
  EnvironmentName:
    Description: An Environment name that will prefix the resources
    Type: String
  SecurityGroupCIDR:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: 9
    MaxLength: 18
    Default: 0.0.0.0/0
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.

#Mappings:

#Conditions:

Resources:
  # here we define a SSH security group that will be used in the entire company
  MySSHSecurityGroup:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group.html
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: !Ref 'SecurityGroupCIDR'
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName        
Outputs:
  StackSSHSecurityGroup:
    Description: The SSH Security Group for our Company
    Value: !Ref MySSHSecurityGroup
    Export:
      Name: SSHSecurityGroup
