---
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
AWSTemplateFormatVersion: "2010-09-09"

Description: 'AWS Cloudformation template Flow logs for VPC'

Metadata:
  License: Apache-2.0

Parameters:
  MyVPC:
    Description: VPC to Operate in
    Type: AWS::EC2::VPC::Id

  TrafficType:
    Description: 'The type of traffic to log.'
    Type: String
    Default: REJECT
    AllowedValues:
    - ACCEPT
    - REJECT
    - ALL

  RetentionInDays:
    Description: 'Specifies the number of days you want to retain log events.'
    Type: Number
    Default: 14
    AllowedValues: [1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 3653]

  LogFilePrefix:
    Description: 'Optional The log file prefix.'
    Type: String
    Default: ''
#Mappings:

#Conditions:

Resources:
  LogBucket:
    Type: AWS::S3::Bucket
    Properties: {}

  LogBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref LogBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: AWSLogDeliveryWrite
          Effect: Allow
          Principal:
            Service: 'delivery.logs.amazonaws.com'
          Action: 's3:PutObject'
          Resource: !Sub '${LogBucket.Arn}/${LogFilePrefix}/AWSLogs/${AWS::AccountId}/*'
          Condition:
            StringEquals:
              's3:x-amz-acl': 'bucket-owner-full-control'
        - Sid: AWSLogDeliveryAclCheck
          Effect: Allow
          Principal:
            Service: 'delivery.logs.amazonaws.com'
          Action: 's3:GetBucketAcl'
          Resource: !GetAtt 'LogBucket.Arn'

  VPCFlowLog:
    Type: AWS::EC2::FlowLog
    DependsOn: LogBucket
    Properties:
      LogDestination: !Sub '${LogBucket.Arn}/${LogFilePrefix}/'
      LogDestinationType: s3
      ResourceId: !Ref MyVPC
      ResourceType: 'VPC'
      TrafficType: !Ref TrafficType

Outputs:
  StackName:
    Description: 'Stack name.'
    Value: !Sub '${AWS::StackName}'
  LogBucketName:
    Description: 'Log bucket name.'
    Value: !Ref LogBucket
